### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by Wnt** [dcaliste/maep-qt#16]
Could you please add build instructions or make the project work out of the box with SailfishSDK? When I import the maep.pro in to the SailfishOS IDE the ide doesn't pick up the .spec file from ../rpm/ directory. How can I make the IDE to use it?

**Comment by dcaliste** [comment]
I will give a look, but I'm not using the IDE, as you can guess. Currently, my environment is :

* develop in my favorite editor (emacs) ;
* keep an ssh session on the mersdk virtual box ( ssh -p 2222 -i ~/SailfishOS/vmshare/ssh/private_keys/engine/mersdk mersdk@localhost) ;
* in the mersdk box, copy all sources in /home/deploy (cp -rp ~/share/maep /home/deploy), ~/share is your true home directory. Go into (cd /home/deploy/maep).
* build there (mb2 -t SailfishOS-armv7hl -s rpm/sailfish-office.spec build).
* copy the generated RPM to the phone and install there.

But I understand that people wants to use the QtCreator IDE. I'll give a look.

**Comment by dcaliste** [comment]
Ok, I've adapted the sources to follow QtCreator conventions. Opening the pro file should now work.
