### ISSUE TITLE
Maep-qt breaks with Qt 5.6

### ISSUE THREAD

**Issue by pvuorela** [dcaliste/maep-qt#24]
harbour-maep-qt: symbol lookup error: harbour-maep-qt: undefined symbol: _ZNK13QQmlValueType10metaObjectEv

Not surprising, it's using private Qt classes: maep.pro:QT += qml-private core-private

**Comment by dcaliste** [comment]
Yes, I've found only this solution to circumvent limitations in allowed Qt libraries and QML bindings in Harbour : to ship them inside Mæp (if I remember, it's done for QML binding of QtCoordinates and QtLocation and for FolderListModel)…

For now, a simple recompilation over Qt5.6 (and maybe an upgrade of my local copy of Qt sources) will solve the issue I guess (as soon as a SDK with Qt5.6 is available, I'll do it during the early access period).

* For the FolderListModel, I'll upgrade to use the new file picker from Silica (I think I've seen something like that recently).
* For Location and Coordinates QML binding from QtLocation, well I hope they will be authorized after the migration to Qt5.6…

**Comment by dcaliste** [comment]
Good news, I'm using only QtPositioning which is allowed since a long time. I didn't notice because I was importing 5.0, but only 5.2 is allowed… Remains the FolderListModel stuff.

Besides, the build with Qt5.2 SDK works directly on a Qt5.6 device with the last master.

**Comment by revad** [comment]
Won't start in recently-released Jolla SFOS 2.1.0.9

**Comment by dcaliste** [comment]
Master is working. I'm going to submit it to Harbour in the coming days.

**Comment by dcaliste** [comment]
1.4.4-2 submitted to amster.
